name: Docker images verification
# This workflow is triggered on pushes and pull requests to the repository.
on: [push, pull_request, pull_request_target]


jobs:
  build:
    # This job runs on Linux
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v1
       - uses: ./.github/actions/docker-images-verification
         with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITGUB_PAT }}
          registry: ghcr.io
